# In-Class Programming Activity, Day 8

## Task 1
```{r}
x = c(runif(100, 20,70))
My_data = data.frame(x = x, y = c(5 + 3*x + 2 *rnorm(100))) 

#(2)
plot(My_data)


#3 
LL_line <- function(params){
  m = params[1]  
  b = params[2] 
  sigma = params[3]
  
  sum(log(dnorm(y - (m * x + b), sd = sigma)))
}

#4
testA = LL_line(c(3,5,2))
testB = LL_line(c(4,1,10))

#5
starting_params <- c(4, 1, 10)
best <- optim(starting_params, LL_line, control=list(fnscale = -1))
```


## Task 2 
```{r}
load(url("http://tiny.cc/dcf/Taxi_trips.rda"))


taxi_likelihood <- function(params, data){
  base_fare = params[1]
  per_mile = params[2]
  rate = 1/params[3]
  excess = with(data, fare_amount - (base_fare + per_mile*trip_distance))
  sum(log(dexp(excess, rate) + 0.00000001))
}

starting_params <- c(1, 1, 1/3)
best = optim(starting_params, taxi_likelihood, control = list(fnscale = -1), data = Taxi_trips)

plot(fare_amount ~ trip_distance, data = Taxi_trips)

abline(best$par[1], best$par[2], col="red", lwd=3)
```

## Test statements

```{r}
scoreActivity::score253(8)
```