# In-Class Programming Activity, Day 9

```{r}
poker_deck = c(outer((10 * 2:14), 1:4, '+'))

suits = function(cards) cards %% 10
ranks = function(cards) cards %/% 10

five_cards <- sample(poker_deck, 5)

is_royal_flush = function(five_cards){
  is_straight_flush(five_cards) && min(rank(five_cards)) == 10
}

is_straight_flush = function(five_cards) {
  is_flush(five_cards) & is_straight(five_cards)
}

is_four_of_a_kind = function(five_cards) {
  max(table(ranks(five_cards))) == 4
}


is_full_house = function(five_cards) {
  counts <- table(ranks(five_cards))
  max(counts) == 3 & min(counts) == 2
}

is_flush = function(five_cards) {
  max(table(suits(five_cards))) == 5
}

is_straight = function(five_cards) {
  max(diff(sort(ranks(five_cards)))) == 1
}

is_three_of_a_kind = function(five_cards) {
  max(table(ranks(five_cards))) == 3
}

is_two_pair = function(five_cards) {
  sum(table(ranks(five_cards)) == 2) == 2
}

is_pair = function(five_cards) {
  max(table(ranks(five_cards))) == 2
}


before_draw <- function(...) {
  five_cards <- sample(poker_deck, 5)
  if (is_royal_flush(five_cards)) return("Royal Flush")
  if (is_straight_flush(five_cards)) return("Straight Flush")
  if (is_four_of_a_kind(five_cards)) return("Four")
  if (is_full_house(five_cards)) return("Full House")
  if (is_flush(five_cards)) return("Flush")
  if (is_straight(five_cards)) return("Straight")
  if (is_three_of_a_kind(five_cards)) return("Three")
  if (is_two_pair(five_cards)) return("Two Pair")
  if (is_pair(five_cards)) return("Pair")
  return("Nada")
}


counts <- table(ranks(five_cards))
min(counts) == 2 && max(counts) == 3

table(sapply(1:10000, FUN=before_draw))

```



## Test statements

```{r}
scoreActivity::score253(9)
```