# In-Class Programming Activity, Day 12

```{r}

n_cases = 100
red_mean = c(1,0)
green_mean = c(0, -1)
blue_mean = c(-1, 1)

covar_red = cbind(c(3, -1.7), c(-1.7, 1) )
covar_blue = cbind(c(2, 1.5), c(1.5, 3) )

One= cbind(rnorm(n_cases), rnorm(n_cases))
Two = cbind(rnorm(n_cases), rnorm(n_cases))
Three = matrix(rnorm(2 * n_cases), ncol=2, nrow=n_cases)


Red =  One %*% chol(covar_red) + matrix(red_mean, nrow = n_cases, ncol = 2, byrow = TRUE)
Green = Two %*% chol(covar_red) + matrix(green_mean, nrow = n_cases, ncol = 2, byrow = TRUE)
Blue = Three %*% chol(covar_blue) + matrix(green_mean, nrow = n_cases, ncol = 2, byrow = TRUE)

Red = data.frame(x = Red[,1], y = Red[,2], class="red", stringsAsFactors = FALSE)
Green = data.frame(x = Green[,1], y = Green[,2], class="green", stringsAsFactors = FALSE)
Blue = data.frame(x = Blue[,1], y = Blue[,2], class="blue", stringsAsFactors = FALSE)

Same_sigma = rbind(Red, Green)
Different_sigma = rbind(Red, Blue)

#plot(y ~ x, data=Same_sigma, col=alpha(Same_sigma$class, .02), pch=20)
#plot(y ~ x, data=Different_sigma, col=alpha(Different_sigma$class, .02), pch=20)

library(MASS)
mod_LDA_one <- lda(class ~ x + y, data = Same_sigma)

test_LDA_one <- predict(mod_LDA_one, newdata = Same_sigma)


table(Same_sigma$class, test_LDA_one$class)

mod_QDA_one <- MASS::qda(class ~ x + y, data = Same_sigma)
test_QDA_one <- predict(mod_QDA_one, newdata = Same_sigma)
table(Same_sigma$class, test_QDA_one$class)

mod_LDA_two <- MASS::lda(class ~ x + y, data = Different_sigma)
mod_QDA_two <- MASS::qda(class ~ x + y, data = Different_sigma)
test_LDA_two <- predict(mod_LDA_two, newdata = Different_sigma)
test_QDA_two <- predict(mod_QDA_two, newdata = Different_sigma)
table(Different_sigma$class, test_LDA_two$class)
table(Different_sigma$class, test_QDA_two$class)


```



## Test statements

```{r}
scoreActivity::score253(12)
```